#!/bin/bash
source util.sh

cmd "mkdir hello"
cmd "cd hello"
cmd "git init"
git config user.name "Alice"
git config user.email "alice@qoo.con"

cmd "find .git/objects/"
msg "[Objects, Hashes, and Blobs]"
cmd "echo 'hello world' > hello.txt"
cmd "git add hello.txt"
cmd "find .git/objects/"
cmd "git cat-file -p 3b18e"
msg "[Files and Trees]"
cmd "git ls-files -s"
cmd "git write-tree"
cmd "find .git/objects/"
cmd "git cat-file -p 68aba"
msg "[Tree Hierarchies]"
cmd "mkdir subdir"
cmd "cp hello.txt subdir/"
cmd "git add subdir/hello.txt"
cmd "git write-tree"
cmd "git cat-file -p 49241"
cmd "find .git/objects/"
msg "[Commits]"
cmd "echo 'Commit a file that says hello' | GIT_AUTHOR_DATE='1970-01-01 00:00' GIT_COMMITTER_DATE='1970-01-01 00:01' git commit-tree 49241"
cmd "git cat-file -p cfc0f"
msg "[Tags]"
cmd "GIT_COMMITTER_DATE='1970-01-01 00:02' git tag -m 'Tag version 1.0' V1.0 cfc0f"
cmd "git cat-file -p 74d60"
